<?php
/**
 * Created by PhpStorm.
 * User: gordon
 * Date: 7/5/2561
 * Time: 11:34 น.
 */
namespace Suilven\TimeZones\Tests;

use Carbon\Carbon;
use SilverStripe\Dev\SapphireTest;
use SilverStripe\ORM\FieldType\DBDatetime;
use Suilven\TimeZones\TimeZoneHelper;

class TimeZoneHelperTest extends SapphireTest
{
    /** @var TimeZoneHelper */
    protected $helper;

    public function setUp()
    {
        $this->helper = new TimeZoneHelper();
        return parent::setUp(); // TODO: Change the autogenerated stub
    }


    /**
     * @param null|string $timezone Optional timezone, otherwise will default to PHP setting
     */
    public function test_asia() {
        // from http://support.sas.com/documentation/cdl/en/lrdict/64316/HTML/default/viewer.htm#a003169814.htm
        $dateTimeObj = new DBDatetime(' 	2008-09-15T15:53:00+07:00');

        /** @var Carbon $utcTime */
        $utcTime = $this->helper->convertToUTC($dateTimeObj);

        $this->assertEquals('something', $utcTime->toIso8601String());
    }
}
